'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Wireless_Running_Monitor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355329674_disk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355329674_disk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355329731_folderopen1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355329731_folderopen1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355329890_About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355329890_About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355330233_flag_indonesia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355330233_flag_indonesia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355330323_Gnome_System_Log_Out_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355330323_Gnome-System-Log-Out-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355330473_RerunCalibration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355330473_RerunCalibration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355332350_chronometer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355332350_chronometer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355332765_connect_creating() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355332765_connect_creating", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355332809_disconnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355332809_disconnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355334115_button_stop_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355334115_button_stop_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355335698_gtk_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355335698_gtk-clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1355340724_RejectCalibration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1355340724_RejectCalibration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property gunshot() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("gunshot", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property run_unnes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run-unnes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
